### ISSUE TITLE
remove whole plant phenological stage

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#16]
We will just use plant phenological stage, and then specify if it applies to a whole plant or a population at the instance level. 

This is simpler, and it also solves the problem that we can't use a cardinality restriction on whole plant phenological stage with current reasoners (because has participant is not a simple property).

We should change the names of all the subclasses to follow the pattern of "vascular leaf plant phenological stage".

**Comment by rlwalls2008** [comment]
@stuckyb: Maybe you could add a subclass axiom to the parent term (which I think is plant phenological stage) saying "has participant only (whole plant OR plant part or plant population)". I think plant population is in PCO, and if it isn't, we can add it.

**Comment by stuckyb** [comment]
How are we feeling about this by now?  Currently, all of our traits and stages are defined in terms of "whole plants", and that is consistent with NPN's and PEP725's view of phenological stages/phases.  I think that the original concerns here about cardinality restrictions are no longer relevant, because we now use "subclass of" axioms to define our classes and none of the logical definitions use cardinality restrictions.  Another question is whether phenological stages, as we've defined them, can really be applied to plant populations.  All of our human-readable definitions are written in terms of things that an individual plant is doing, and this makes the most sense to me.  After all, the "phenological stage" of a plant population could only be defined in terms of what the individual plants in the population are doing.

**Comment by robgur** [comment]
Brian, I think I agree --- in cases of working at the population level,
we are aggregating from the individual plant level -  but this might verge
into areas where we move from BCO to PCO, so perhaps Ramona can chime in
here.

**Comment by ramonawalls** [comment]
NPN and PEP both measure stages on populations for clumps of small plants, so we need to be sure the definitions still encompasses that. If, instead of saying "has participant only (whole plant OR plant part or plant population)" we added the subclass axiom "has participant some whole plant" it would still be logically correct, because plant populations have two or more whole plants as part.

This prevents us from defining phenological stages as stages of a plant part, but that is probably for the best. To describe the phenology of a plant part, people should be using PO plant structure development stages.

Both of these points should be added to a comment. At some point, we are going to need to add comments to many of the definitions to make sure their meaning is clear to someone who does not have the skills or time to follow all the implications of the logical definitions.

**Comment by robgur** [comment]
Agree.
   Maybe this also better provides an on-ramp for potentially integrating
phenocam data down the road, where ostensibly there is an aggregate measure
of phenology per image that includes populations of different plants.
  Also,it does appear that sometimes phenocam images are split into
constitute populations of species before being analyzed, much more akin to
the above...

**Comment by stuckyb** [comment]
I modified the text definition of 'plant phenological stage' so that it no longer applies to parts of plants, and I think we should be good to go.  All of our logical definitions for phenological stages use 'has participant' SOME 'whole plant'..., which, as Ramona pointed out, makes them valid for populations, too.

Note that all of our traits are still defined in terms of whole plants, but I don't think that is a problem.  Does anyone else?

**Comment by ramonawalls** [comment]
Maybe this change hasn't been pushed yet? When I look at PPO, I still see plant part in the definition of plant phenological stage. 

Do you want to change it such that the logical definition of plant phenological stage includes 'has participant' some 'whole plant', so that it does not need to be specified for each subclass? If we are going say that in the text definition, it should probably be explicit in the logical definition.

**Comment by stuckyb** [comment]
Right, it hadn't been pushed yet.  You should see the revised definition now.

Currently, 'plant phenological stage' does not have a logical definition.  I didn't know how to capture "encompasses some part of the life of a whole plant" using set operators and restrictions.  Should we try to come up with something?

Maybe it would be enough just to say SUBCLASS OF 'spatiotemporal region' AND ('has participant' SOME 'whole plant')?

That's not really much of a definition, but it captures some information about the intent.

However, I'm not sure how much this really helps us, because we will still need to include ('has participant' SOME 'whole plant') in the definition of every subclass.  Otherwise, there would be no way to say anything about the qualities of a plant that participates in a given phenological stage.

**Comment by ramonawalls** [comment]
I see now why we need to include has participant whole plant in every subclass definition. However, I still think it would be useful to place at least a minimal restriction on the parent class. 

In terms of defining "encompasses some part of the life of a whole plant", I think that means that the stage has a participant some plant that is participating in a whole plant development stage that is part of a life of whole plant. Since every sporophyte and gametophyte development stage is part of a life of whole plant, that just means that it is participating in some whole plant development stage. This sounds like a tautology - like we should just say that a plant phenological stage is a whole plant development stage, but it isn't, because phenological stages can apply to populations as well.

We could say:
SUBCLASS OF 'spatiotemporal region' AND ('has participant' SOME ('whole plant' THAT 'participates in' SOME 'whole plant development stage'))

I guess "THAT 'participates in' SOME 'whole plant development stage'" is just a way of saying the plant is alive, and that the stages don't apply to dead plants.

**Comment by ramonawalls** [comment]
@stuckyb I'd like to close this issue before we do a release. Do you see any problem with add 

SUBCLASS OF 'spatiotemporal region' AND ('has participant' SOME 'whole plant')

to plant phenological stage, based on our discussion above?

**Comment by stuckyb** [comment]
@ramonawalls, what do you think about this:
```
'plant phenological stage' THAT 'has participant' SOME (
    'whole plant' THAT 'participates in' SOME 'plant growth cycle'
)
```
That brings in one other condition that is in the text definition.

This issue also relates to issue #31.  We might want to discuss our text definition and the comment for 'plant phenological stage'.

**Comment by ramonawalls** [comment]
@stuckyb I think you meant 

'spatiotemporal region' THAT 'has participant' SOME (
    'whole plant' THAT 'participates in' SOME 'plant growth cycle'
)

because the class we are defining is plant phenological stage and we no longer have whole plant phenological stage as a class. If that is the case, then, yes, I agree that it would be good to add the criterion of participating in a plant growth cycle.

I should have put my comment on issue 31 instead of here, but I think the two issues are kind of muddle up.
