### ISSUE TITLE
bco_ppo_import_module.owl points to bad URL For bco

### ISSUE THREAD

**Issue by jdeck88** [PlantPhenoOntology/PPO#20]
The source is pointing to "http://purl.obolibrary.org/obo/bco/releases/2015-04-10/bco.owl" which gives a 404 error.

It should actually be:
http://purl.obolibrary.org/obo/bco/bco.owl

which redirect properly to: 

https://raw.githubusercontent.com/BiodiversityOntologies/bco/master/releases/2015-04-10/bco.owl

**Comment by stuckyb** [comment]
That URL is coming directly from the versionIRI tag in the BCO.  If it is invalid, it needs to be updated in the BCO.

**Comment by stuckyb** [comment]
@jdeck88, is this still an issue?

**Comment by jdeck88** [comment]
I believe it is... however, i'm not 100% sure.  I'm going to dive into code next week again... been out for holidays and family last couple of weeks so haven't looked at this in awhile.

**Comment by ramonawalls** [comment]
http://purl.obolibrary.org/obo/bco/bco.owl now redirects to https://raw.githubusercontent.com/tucotuco/bco/master/bco.owl, so it should be pulling the correct file. However, the bco module still includes http://purl.obolibrary.org/obo/bco/releases/2015-04-10/bco.owl as the source. This is strange, because https://github.com/PlantPhenoOntology/PPO/blob/master/src/imports/imported_ontologies.csv is pointing to the PURL for BCO. Is it possible, @stuckyb, that you have not updated the BCO import module since early December? If so, that would explain the inconsistency.

**Comment by stuckyb** [comment]
Yes, indeed!  I've updated the BCO module and it now points to the latest release.  @jdeck, does this resolve the issue?

**Comment by jdeck88** [comment]
yes, that resolves the issue!
