### ISSUE TITLE
Need a description and license. 

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/PPO#23]
I will add a brief description to this repo, which will also be displayed on the OBO Library page (http://obofoundry.github.io/). We can always edit it. 

We need a license for both this repo and for the ontology. For the ontology, the OBO Foundry recommends CC-BY. I will add that for now, because we can always change it to CC-0 if folks want, but we can't change from a less restrictive to a more restrictive license.

**Comment by stuckyb** [comment]
The description looks good, but I'll suggest a minor change.  Instead of, "An ontology for integrating plant phenological data across sources and scales.", how about, "An ontology for describing the phenology of individual plants and populations of plants, and for integrating plant phenological data across sources and scales."

The license sounds good to me, Ramona.  I prefer CC-BY over CC-0.

**Comment by robgur** [comment]
+1

**Comment by ramonawalls** [comment]
Agreed. I'll leave this open until I have a chance to update the OBO Foundry info.

**Comment by ramonawalls** [comment]
Done.
