### ISSUE TITLE
NTR: classes for unfolding and unfolded leaves

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#40]
NPN distinguishes expanding leaves into two categories: those that are still in the process of unfolding and those that are unfolded but still expanding. This distinction is not made for young leaves versus mature leaves, but rather when defining initial growth stages, such as when bud burst is considered over.

While this distinction is useful for precision, it is not strictly necessary for mapping to the PO (and therefore current PPO classes), because both stages can map to PO: expanding leaf. If we are to add new classes for this, we should first have a use case where it is important to make the distinction for data analysis.

**Comment by ramonawalls** [comment]
I not sure how this is handled in NPN for species that don't have any folding, that is, that just grow from meristem and expand. For cotyledons, NPN clarifies: "For seedlings, "initial" growth includes the presence of the one or two small, round or elongated leaves (cotyledons) before the first true leaf has unfolded." There are also definitions for grasses and rushes. I think there is still a gap on how to define new growth on shoot-born shoot systems for herbaceous plants, e.g., a new leaf on a branch that develops from a meristem without a bud and does not start life folded up.

**Comment by edenny** [comment]
As mentioned in issue #37, the use case for this might be the "Leaves" phenophase. It does not start on a plant until there is one true leaf whose whole tiny length has emerged from the bud and is visible without tearing the bud scales off. Thus there could be lots of tips of true leaves visible for a week or more, before the first one emerges far enough from the bud to be constitute the start of our "Leaves" phenophase.

I feel like it might be necessary to add this precision into the ontology because a) there is a lot of research surrounding the start of leafing in moist temperate regions, and b) the end point of a breaking leaf bud (which is the beginning of "Leaves") is not very precisely defined.  

Also note, in case it helps, that the start of NPN "Leaves" coincides with BBCH 11, or at least is intended to do so.

**Comment by edenny** [comment]
There is certainly ambiguity in the term "unfolded" for many forb species. When asked for a given species, we tend to say the first leaf is "unfolded" once you can recognize the adult leaf shape, which is often (but not always in the case of forbs) a much smaller size.

For woody species with naked buds (e.g. Hamamelis), we have some taxon-specific definitions that tend to equate "breaking leaf buds" with the first green on the tiny exposed leaf is visible, and the first "unfolded" leaf with the point when the leaf opens like a book to be more or less flat. But I consider these corner cases we don't need to fret over.

For dryland species, there are often no buds visible and tiny leaves just seem to appear out of nowhere. In these species, we don't even bother to include a breaking leaf bud or initial growth phenophase because it is usually happens too fast to witness. Visible vegetative growth starts with "Leaves" and/or "Young leaves". The current definition would work fine for those cases, but I don't think the addition of language about "unfolding/unfolded" would get in the way.

**Comment by ramonawalls** [comment]
Add two new stages:

vascular leaf unfolding stage: A {vascular leaf expansion stage} during which a {vascular leaf} participates in the process of unfolding.
comment: This stage ends when a leaf is considered unfolded, which varies by species. 
(@edenny - please add a comment including the different definitions of unfolded in NPN. I'm afraid I'll miss some.)

vascular leaf expanding but unfolded stage: A {vascular leaf expansion stage} during which a {vascular leaf} has completed the process of unfolding but is still expanding in size.

We will also need corresponding classes for unfolding leaf presence and expanding but unfolded leaf presence.

**Comment by edenny** [comment]
How about this for a comment? Too long? If you generally approve, I'll need to check with Kjell to make sure this is consistent with PEP.

This stage ends when a leaf is considered unfolded, which varies by species. For broadleaf woody species, a leaf is considered to be unfolded once its entire length has emerged from a breaking bud, stem node or growing stem tip; for forbs and woody species with naked buds, once the leaf blade has unfolded enough to appear more or less like a small version of the adult leaf; for most conifers, once a needle has spread away from the developing stem enough that its point of attachment to the stem is visible; for pines, once a needle begins to spread away at an angle from other needles in the bundle; for grasses, once the leaf blade unrolls slightly from around the stem and begins to fall away at an angle from the stem; for sedges, once the leaf has grown long enough that the two halves of the blade have begun to spread apart like an open book; for rushes, once the exposed, green portion of the leaf has reached approximately 5 cm in length.

**Comment by edenny** [comment]
I am not sure you need to create all those classes. Would it be enough to just create a supporting class for {unfolded}, and for those existing classes with definitions that include "....that has not yet produced a {true leaf}" extend them to say "....that has not yet produced a {true leaf} that has {unfolded}"?

For instance, we would not likely map a whole plant to {unfolding leaf presence}. We simply use the point when "unfolding" has ended (and "unfolded" has been achieved) for the first leaf from a bud or shoot, in order to determine when that bud or shoot has moved out of the initial growth/bud breaking phenophase and into the leaf phenophase. Then we look at the whole plant to determine whether it has buds or shoots in either or both of the {initial growth/breaking leaf bud presence} and {leaf presence} stages.

**Comment by ramonawalls** [comment]
@edenny - re. the comment for unfolding leaves, long comments are fine. Better to be thorough! Please do check with Kjell to see if anything is missing. We can always update the comment after data ingest, so there is no hurry, and we can spend time tweaking it.

re.  Your second comment, we could define a quality called unfolded, as you suggest, but to be consistent with the design patter we have been using, we need to create the presence classes. Those are what we use to logically infer that plants belong to a certain stage. You are right that we probably don't need the classes for unfolding leaves, only unfolded but still expanding. I will start with that and see if we get the inferences we need to define the leaf stages.

**Comment by ramonawalls** [comment]
fixed with commit 61f5e34

**Comment by ramonawalls** [comment]
Updated comment for unfolding leaves: 
This stage ends when a leaf is considered unfolded, which varies by species, but generally occurs once the leaf blade has unfolded enough to appear more or less like a small version of the adult leaf. For species with scaled buds, this is generally once the entire leaf blade has emerged from a breaking bud; for conifers, once a needle begins to spread away at an angle from the developing stem or from other needles in a bundle (e.g. pines); for grasses, once the leaf blade unrolls slightly from around the stem and begins to fall away at an angle; for sedges, once the leaf has grown long enough that the two halves of the blade have begun to spread apart like an open book; for rushes, once the exposed, green portion of the leaf has reached a specified length.

**Comment by stuckyb** [comment]
So, when I look at the PPO, I see the following:

* vascular leaf phenological stage
    * non-senescing leaf phenological stage
        * expanding leaf phenological stage
        * mature leaf phenological stage
        * unfolded leaf phenological stage
        * young leaf phenological stage
    * senescing leaf phenological stage

This doesn't seem to match the comments above.  Am I missing something?  I expected to see 'vascular leaf unfolding stage' and 'vascular leaf unfolded expanding stage', both as subclasses of 'expanding leaf phenological stage'.

Also, 'mature leaf phenological stage' and 'unfolded leaf phenological stage' appear to be identical.

**Comment by ramonawalls** [comment]
@stuckyb It was necessary to make a full set of plant structure development stages to logically define the new/revised classes for young leaf, mature leaf, and unfolded leaf. Likewise, it was necessary to make the corresponding traits to define the new/revised classes for young leaf phenological stage, mature leaf phenological stage, and unfolded leaf phenological stage. However, given our current mappings to NPN and PEP, there was no need to create phenological stages for vascular leaf unfolding phenological stage' and 'vascular leaf unfolded expanding phenological stage'. 

This is why you don't see those classes under the vascular leaf phenological stage hierarchy, but do see corresponding classes under the plant structure development stage hierarchy.

**Comment by ramonawalls** [comment]
@stuckyb The identical nature of  'mature leaf phenological stage' and 'unfolded leaf phenological stage' is a copy paste error. They should be defined differently. I'm still having some issues finessing Open Office. In any case, we need to update the definition of  'unfolded leaf phenological stage' based on issue #37.

**Comment by ramonawalls** [comment]
Note that it is not actually necessary to create classes for young leaf, mature leaf, and unfolded leaf, only the corresponding development stages, traits, and phenological stages.

**Comment by stuckyb** [comment]
Okay, thanks, Ramona.  I still think there are problems with the class hierarchy.  E.g., shouldn't 'expanding leaf phenological stage' be a subclass of 'young leaf phenological stage', assuming the text definitions are correct?

**Comment by ramonawalls** [comment]
Yes. Please to change it. Ideally that would be inferred, but I don't have the bandwidth to think about how that would happen right now.
