### ISSUE TITLE
leaf stage names

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/ppo#45]
Most of our leaf-related phenological stage names follow the pattern "_adjective_ leaf phenological stage".  For consistency, I propose we change "leaf expansion phenological stage" to "expanding leaf phenological stage".

A second inconsistency is in the names "non-senescing leaf phenological stage" and "senescent leaf phenological stage".  These classes are mutually exclusive, so it would be nice if the names used terminology consistently.  E.g., use either "senescent" or "senescing" for both names.

**Comment by robgur** [comment]
+1

On Jun 21, 2017 7:40 AM, "stuckyb" <notifications@github.com> wrote:

Most of our leaf-related phenological stage names follow the pattern "
*adjective* leaf phenological stage". For consistency, I propose we change
"leaf expansion phenological stage" to "expanding leaf phenological stage".

A second inconsistency is in the names "non-senescing leaf phenological
stage" and "senescent leaf phenological stage". These classes are mutually
exclusive, so it would be nice if the names used terminology consistently.
E.g., use either "senescent" or "senescing" for both names.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PlantPhenoOntology/ppo/issues/45>, or mute the thread

**Comment by stuckyb** [comment]
Anyone have thoughts on "senescent" vs "senescing"?  I think I like 
"senescing" better because it reflects that senescing is a process and 
not just an end state (I suspect that fits better with what observers 
actually record).  Ramona and/or Ellen should weigh in on this, though.

**Comment by ramonawalls** [comment]
Agree with the suggestions. I think senescing is better than senescent, because that is how we define it.

**Comment by stuckyb** [comment]
I made these changes with commit c79c90e, but now I wonder if the term we want to use is "true leaf", not "vascular leaf".  "vascular leaf" includes cotyledons, and our stages and traits concern vascular leaves that are not cotyledons; i.e., true leaves.

**Comment by stuckyb** [comment]
Fixed with commit c79c90e.
