### ISSUE TITLE
pollen-releasing traits

### ISSUE THREAD

**Issue by edenny** [PlantPhenoOntology/ppo#71]
We have 3 pollen-releasing traits:
{pollen-releasing floral structure presence} 
{pollen-releasing flower head presence}
{pollen-releasing flower presence}

Do we need all 3 of these for some reason, or is it enough just to have {pollen-releasing flower presence} since pollen only comes from individual flowers ,and flower heads and floral structures by definition include individual flowers?

**Comment by ramonawalls** [comment]
Discussed with @edenny. Flower head terms were added for NPN data for grasses and sedges (not sunflowers), since it can be hard to distinguish whether or not an individual flower is open or closed but you can always tell if a flower head is present.  If pollen releasing flowers are present, and we know the species has flower heads (ie. inflorescenses), we don't need the pollen producing flower head term, because queries include the taxon, and the researcher will know that there are flower heads. NPN only uses pollen releasing flowers.

However, if we were using a structure at all, we just included all the terms, even though it creates some redundancy.

By the same reasoning that pollen releasing flower head presence is not needed, technically, flower head presence is not needed either, because if you scored it as flowers present, it would provide the same information, if you know that the species has inflorescences. Nonetheless, there is not harm in keeping this set of terms, because from the flower head presence terms you can reason the flower presence terms, and it allows you to be a little more specific.

**Comment by ramonawalls** [comment]
Outcome: we will keep the term.
